---
- hosts: localhost

  tasks:
  - name: ensure apache is at the latest version
    apt:
      name: vim
      state: latest
      
  - name: ensure apache is at the latest version
    apt:
      name: nginx
      state: latest
  - name: Enable service httpd, and not touch the running state
    service:
      name: nginx
      enabled: yes
      state: stopped
