---
- hosts: localhost

  tasks:      
  - name: ensure nginx is installed at the latest version
    apt:
      name: nginx
      state: latest
  - name: Enable service nginx, and state should be started
    service:
      name: nginx
      enabled: yes
      state:  started
