---
- hosts: localhost

  tasks:
  - name: ensure apache is at the latest version
    apt:
      name: vim
      state: latest
      
  - name: ensure apache is at the latest version
    apt:
      name: nginx
      state: latest
