---
- hosts: localhost

  tasks:
  - name: ensure lighttpd is installed at the latest version
    apt:
      name: lighttpddd
      state: absent
  - name: Enable service lighttpd, and state should be started
    service:
      name: lighttpd
      enabled: no
      state:  stopped
      
  - name: ensure nginx is installed at the latest version
    apt:
      name: nginxxxx
      state: present
  - name: Enable service nginx, and state should be started
    service:
      name: nginx
      enabled: yes
      state:  started
